src/main/java/com/yht/exerciseassist/ResponseResult.java, src/main/java/com/yht/exerciseassist/configuration/SecurityConfig.java, src/main/java/com/yht/exerciseassist/domain/DateTime.java, src/main/java/com/yht/exerciseassist/domain/chat/ChatList.java, src/main/java/com/yht/exerciseassist/domain/chat/ChatMessage.java, src/main/java/com/yht/exerciseassist/domain/chat/ChatRoom.java, src/main/java/com/yht/exerciseassist/domain/comment/Comment.java, src/main/java/com/yht/exerciseassist/domain/diary/Diary.java, src/main/java/com/yht/exerciseassist/domain/media/Media.java, src/main/java/com/yht/exerciseassist/domain/member/Member.java, src/main/java/com/yht/exerciseassist/domain/member/controller/MemberController.java, src/main/java/com/yht/exerciseassist/domain/member/dto/SignUpRequestDto.java, src/main/java/com/yht/exerciseassist/domain/member/repository/MemberRepository.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/domain/post/Post.java, src/main/java/com/yht/exerciseassist/exceoption/controller/SignExceptionController.java, src/main/java/com/yht/exerciseassist/exceoption/error/jwt/EmptyJWTTokenExcep.java, src/main/java/com/yht/exerciseassist/exceoption/error/jwt/InvalidJWTTokenExcep.java, src/main/java/com/yht/exerciseassist/exceoption/error/jwt/UnsupportedJWTTokenExcep.java, src/main/java/com/yht/exerciseassist/jwt/JwtTokenProvider.java, src/main/java/com/yht/exerciseassist/jwt/JwtTokenResolver.java, src/main/java/com/yht/exerciseassist/jwt/filter/ExceptionHandlerFilter.java, src/main/java/com/yht/exerciseassist/jwt/filter/JwtAuthenticationFilter.java, src/main/java/com/yht/exerciseassist/jwt/service/JWTService.java
=> refactor : 토큰 재발급 로직 수정, 오토 포맷팅

build.gradle, src/main/java/com/yht/exerciseassist/ExerciseAssistApplication.java, src/main/java/com/yht/exerciseassist/domain/member/dto/SignUpRequestDto.java, src/test/java/com/yht/exerciseassist/domain/member/MemberTest.java, src/test/java/com/yht/exerciseassist/domain/member/controller/MemberControllerTest.java, src/test/java/com/yht/exerciseassist/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/member/service/MemberServiceTest.java
회원가입과 로그인에 관련된 controller, service, repository, domain 단위 테스트 작성
=> test(signUp,signIn) : 회원가입 로그인 테스트 작성

build.gradle, src/main/java/com/yht/exerciseassist/configuration/SecurityConfig.java, src/main/java/com/yht/exerciseassist/domain/DateTime.java, src/main/java/com/yht/exerciseassist/domain/diary/Diary.java, src/main/java/com/yht/exerciseassist/domain/diary/controller/DiaryController.java, src/main/java/com/yht/exerciseassist/domain/diary/dto/ExerciseInfoDto.java, src/main/java/com/yht/exerciseassist/domain/diary/dto/WriteDiaryDto.java, src/main/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepository.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/member/Member.java, src/main/java/com/yht/exerciseassist/domain/member/controller/MemberController.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/exceoption/CustomExceptionHandler.java, src/main/java/com/yht/exerciseassist/exceoption/controller/DiaryExceptionController.java, src/main/java/com/yht/exerciseassist/jwt/SecurityUtil.java, src/test/java/com/yht/exerciseassist/domain/diary/DiaryTest.java, src/test/java/com/yht/exerciseassist/domain/diary/controller/DiaryControllerTest.java, src/test/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/diary/service/DiaryServiceTest.java, src/test/java/com/yht/exerciseassist/domain/member/MemberTest.java, src/test/java/com/yht/exerciseassist/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/member/service/MemberServiceTest.java
=> feat(diary): diary 작성 구현

Dockerfile, src/main/java/com/yht/exerciseassist/domain/diary/BodyPart.java, src/main/java/com/yht/exerciseassist/domain/diary/ExerciseInfo.java, src/main/java/com/yht/exerciseassist/domain/diary/dto/ExerciseInfoDto.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/test/java/com/yht/exerciseassist/domain/diary/controller/DiaryControllerTest.java, src/test/java/com/yht/exerciseassist/domain/diary/service/DiaryServiceTest.java
다이어리 작성 시 운동 부위도 같이 기록할 수 있도록 운동 부위 컬럼 추가.
request에서도 운동 부위 받을 수 있도록 추가 및 수정
=> 수정 배포 : 운동 부위 추가

.gitignore, src/main/resources/application.yml
8080포트 사용 시 정상 작동하는지 배포 테스트하기 위함
=> chore(port) : 포트 번호 변경

src/main/java/com/yht/exerciseassist/domain/diary/controller/DiaryController.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/exceoption/error/ErrorCode.java, src/test/java/com/yht/exerciseassist/domain/diary/controller/DiaryControllerTest.java
=> feat(deleteDiary) : 다이어리 삭제 기능 추가

src/main/java/com/yht/exerciseassist/domain/diary/controller/DiaryController.java, src/main/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepository.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/test/java/com/yht/exerciseassist/domain/diary/DiaryTest.java, src/test/java/com/yht/exerciseassist/domain/diary/controller/DiaryControllerTest.java, src/test/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/diary/service/DiaryServiceTest.java, src/test/java/com/yht/exerciseassist/domain/factory/DiaryFactory.java, src/test/java/com/yht/exerciseassist/domain/factory/MediaFactory.java, src/test/java/com/yht/exerciseassist/domain/factory/MemberFactory.java, src/test/java/com/yht/exerciseassist/domain/media/MediaTest.java, src/test/java/com/yht/exerciseassist/domain/media/service/MediaServiceTest.java, src/test/java/com/yht/exerciseassist/domain/member/MemberTest.java, src/test/java/com/yht/exerciseassist/domain/member/controller/MemberControllerTest.java, src/test/java/com/yht/exerciseassist/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/member/service/MemberServiceTest.java
다이어리 수정 및 삭제 기능에 대한 테스트 코드 추가 & 미디어 삭제 기능 테스트 코드 추가
테스트 코드를 간소화 하기 위해 테스트 시 목 객체를 위한 엔티티 or DTO객체 생성 코드를 Factory 클래스로 추출
=> test(Factory) : 테스트 코드 추가 및 테스트 시 엔티티 객체 생성 코드 추출

src/main/java/com/yht/exerciseassist/domain/accuse/Accuse.java, src/main/java/com/yht/exerciseassist/domain/accuse/AccuseType.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/media/Media.java, src/main/java/com/yht/exerciseassist/domain/media/service/MediaService.java, src/main/java/com/yht/exerciseassist/domain/member/Member.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/exceoption/error/ErrorCode.java
=> feat : 신고 엔티티 추가 

src/main/java/com/yht/exerciseassist/configuration/SecurityConfig.java, src/main/java/com/yht/exerciseassist/domain/media/Media.java, src/main/java/com/yht/exerciseassist/domain/post/Post.java, src/main/java/com/yht/exerciseassist/domain/post/PostType.java, src/main/java/com/yht/exerciseassist/domain/post/WorkOutCategory.java, src/main/java/com/yht/exerciseassist/domain/post/controller/PostController.java, src/main/java/com/yht/exerciseassist/domain/post/dto/WritePostDto.java, src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepository.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java, src/main/java/com/yht/exerciseassist/exceoption/controller/MediaExceptionController.java, src/main/java/com/yht/exerciseassist/exceoption/controller/PostExceptionController.java, src/test/java/com/yht/exerciseassist/domain/diary/controller/DiaryControllerTest.java, src/test/java/com/yht/exerciseassist/domain/factory/PostFactory.java, src/test/java/com/yht/exerciseassist/domain/post/PostTest.java, src/test/java/com/yht/exerciseassist/domain/post/controller/PostControllerTest.java, src/test/java/com/yht/exerciseassist/domain/post/repository/PostRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/post/service/PostServiceTest.java
=> feat : 게시글 작성 기능 추가

src/main/java/com/yht/exerciseassist/exceoption/controller/DiaryExceptionController.java, src/main/java/com/yht/exerciseassist/exceoption/controller/MediaExceptionController.java, src/main/java/com/yht/exerciseassist/exceoption/controller/PostExceptionController.java, src/main/java/com/yht/exerciseassist/exceoption/error/ErrorCode.java
=> fix : 예외처리 문구 수정

.gitignore, src/main/java/com/yht/exerciseassist/configuration/SecurityConfig.java, src/main/java/com/yht/exerciseassist/domain/diary/controller/DiaryController.java, src/main/java/com/yht/exerciseassist/domain/diary/dto/DiaryDetailDto.java, src/main/java/com/yht/exerciseassist/domain/diary/dto/ExerciseInfoDto.java, src/main/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepository.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/post/controller/PostController.java, src/main/java/com/yht/exerciseassist/domain/post/dto/PostDetailRes.java, src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepository.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java, src/main/java/com/yht/exerciseassist/exceoption/error/ErrorCode.java
게시글 상세조회 기능 추가 완료
하지만 댓글 기능 개발 전이라 댓글 제외 작성자와 게시글 정보만 조회 가능
=> feat(postDetail) : 게시글 상세조회 기능 추가

.gitignore, src/main/java/com/yht/exerciseassist/domain/diary/controller/DiaryController.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepositoryCustom.java, src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepositoryImpl.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java, src/test/java/com/yht/exerciseassist/domain/diary/controller/DiaryControllerTest.java, src/test/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/diary/service/DiaryServiceTest.java, src/test/java/com/yht/exerciseassist/domain/factory/DiaryFactory.java, src/test/java/com/yht/exerciseassist/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/post/controller/PostControllerTest.java, src/test/java/com/yht/exerciseassist/domain/post/repository/PostRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/post/service/PostServiceTest.java
게시글, 다이어리 수정할 데이터 조회 기능 테스트 추가
=> test : 수정할 데이터 조회(게시글, 다이어리)기능 테스트

src/main/java/com/yht/exerciseassist/domain/diary/controller/DiaryController.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/media/service/MediaService.java, src/main/java/com/yht/exerciseassist/domain/post/Post.java, src/main/java/com/yht/exerciseassist/domain/post/controller/PostController.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java, src/main/java/com/yht/exerciseassist/exception/error/ErrorCode.java, src/test/java/com/yht/exerciseassist/domain/diary/controller/DiaryControllerTest.java, src/test/java/com/yht/exerciseassist/domain/diary/service/DiaryServiceTest.java, src/test/java/com/yht/exerciseassist/domain/post/controller/PostControllerTest.java, src/test/java/com/yht/exerciseassist/domain/post/service/PostServiceTest.java
=> feat(deletePost) : 게시글 삭제 기능 추가

.gitignore, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/likeCount/LikeCount.java, src/main/java/com/yht/exerciseassist/domain/likeCount/repository/LikeCountRepository.java, src/main/java/com/yht/exerciseassist/domain/member/Member.java, src/main/java/com/yht/exerciseassist/domain/member/repository/MemberRepository.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/domain/post/Post.java, src/main/java/com/yht/exerciseassist/domain/post/controller/PostController.java, src/main/java/com/yht/exerciseassist/domain/post/dto/PostDetailRes.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java, src/main/java/com/yht/exerciseassist/domain/refreshToken/RefreshToken.java, src/main/java/com/yht/exerciseassist/exception/controller/DiaryExceptionController.java, src/main/java/com/yht/exerciseassist/exception/controller/PostExceptionController.java, src/main/java/com/yht/exerciseassist/exception/error/ErrorCode.java, src/main/java/com/yht/exerciseassist/jwt/service/JWTService.java, src/test/java/com/yht/exerciseassist/domain/factory/PostFactory.java, src/test/java/com/yht/exerciseassist/domain/member/MemberTest.java, src/test/java/com/yht/exerciseassist/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/post/PostTest.java, src/test/java/com/yht/exerciseassist/domain/post/service/PostServiceTest.java
좋아요 기능 구현 및 멤버 정보와 토큰 값이 같이 조회되는 경우를 줄이기 위해 토큰 테이블 분리
=> feat : 좋아요 기능 구현, refreshToken 테이블 분리

src/main/java/com/yht/exerciseassist/configuration/SecurityConfig.java, src/main/java/com/yht/exerciseassist/domain/accuse/Accuse.java, src/main/java/com/yht/exerciseassist/domain/accuse/controller/AccuseController.java, src/main/java/com/yht/exerciseassist/domain/accuse/dto/AccuseReq.java, src/main/java/com/yht/exerciseassist/domain/accuse/repository/AccuseRepository.java, src/main/java/com/yht/exerciseassist/domain/accuse/service/AccuseService.java, src/main/java/com/yht/exerciseassist/domain/post/dto/WritePostDto.java, src/main/java/com/yht/exerciseassist/exception/controller/AccuseExceptionController.java, src/test/java/com/yht/exerciseassist/domain/accuse/controller/AccuseControllerTest.java, src/test/java/com/yht/exerciseassist/domain/accuse/service/AccuseServiceTest.java, src/test/java/com/yht/exerciseassist/domain/factory/AccuseFactory.java
=> feat : 게시글 신고 기능 추가

src/test/java/com/yht/exerciseassist/domain/factory/MemberFactory.java, src/test/java/com/yht/exerciseassist/domain/member/controller/MemberControllerTest.java, src/test/java/com/yht/exerciseassist/domain/member/service/MemberServiceTest.java
=> test : 마이페이지 조회 기능 테스트

.gitignore, build.gradle, src/main/java/com/yht/exerciseassist/configuration/EmailConfig.java, src/main/java/com/yht/exerciseassist/configuration/SecurityConfig.java, src/main/java/com/yht/exerciseassist/email/controller/EmailController.java, src/main/java/com/yht/exerciseassist/email/dto/EmailReqDto.java, src/main/java/com/yht/exerciseassist/email/dto/EmailResDto.java, src/main/java/com/yht/exerciseassist/email/service/EmailService.java, src/main/java/com/yht/exerciseassist/exception/controller/MailExceptionController.java, src/main/java/com/yht/exerciseassist/exception/error/MailSendFailException.java, src/main/resources/application.yml
회원가입, 아이디&비밀번호 찾기 기능을 위한 이메일 인증 기능 구현
=> feat : 이메일 인증 기능 추가

src/main/java/com/yht/exerciseassist/domain/diary/BodyPart.java, src/main/java/com/yht/exerciseassist/domain/diary/dto/DiaryDetailDto.java, src/main/java/com/yht/exerciseassist/domain/diary/dto/DiaryEditData.java, src/main/java/com/yht/exerciseassist/domain/diary/dto/ExerciseInfoResDto.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/post/PostType.java, src/main/java/com/yht/exerciseassist/domain/post/WorkOutCategory.java, src/main/java/com/yht/exerciseassist/domain/post/controller/PostController.java, src/main/java/com/yht/exerciseassist/domain/post/dto/PostListDto.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java, src/test/java/com/yht/exerciseassist/domain/diary/service/DiaryServiceTest.java, src/test/java/com/yht/exerciseassist/domain/factory/DiaryFactory.java, src/test/java/com/yht/exerciseassist/domain/post/service/PostServiceTest.java
Enum 타입을 Key-value 형식으로 변환하여 프론트에서 Enum타입을 알아보기 쉽게 수정
=> refactor : Enum 타입 Key-value 형식 변환

src/main/java/com/yht/exerciseassist/domain/comment/Comment.java, src/main/java/com/yht/exerciseassist/domain/comment/controller/CommentController.java, src/main/java/com/yht/exerciseassist/domain/comment/service/CommentService.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java, src/main/java/com/yht/exerciseassist/exception/controller/CommentExceptionController.java, src/main/java/com/yht/exerciseassist/exception/error/ErrorCode.java, src/test/java/com/yht/exerciseassist/domain/comment/controller/CommentControllerTest.java, src/test/java/com/yht/exerciseassist/domain/comment/service/CommentServiceTest.java, src/test/java/com/yht/exerciseassist/domain/post/service/PostServiceTest.java
=> feat(deleteComment) : 댓글 삭제 기능 추가

src/main/java/com/yht/exerciseassist/ExerciseAssistApplication.java, src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepository.java, src/main/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepository.java, src/main/java/com/yht/exerciseassist/domain/emailCode/EmailCode.java, src/main/java/com/yht/exerciseassist/domain/emailCode/repository/EmailCodeRepository.java, src/main/java/com/yht/exerciseassist/domain/emailCode/service/EmailService.java, src/main/java/com/yht/exerciseassist/domain/member/repository/MemberRepository.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepository.java
이메일 인증 시 5분 뒤 인증 만료를 위해 5분 지난 데이터 db에서 삭제, 멤버 탈퇴 시 한달 뒤 데이터 삭제
=> feat : 자동삭제 기능 추가

.gitignore, src/main/resources/log4j2.xml
=> chore : 빌드 시 xml파일 삭제되는 문제 해결

src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/exception/error/ErrorCode.java
보안을 위해 로그인 실패 시 아이디, 비밀번호 중 무엇이 틀렸는지 알려주지 않게 변경
=> refactor : 로그인 실패 예외 메시지 수정

src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepository.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java
게시글 삭제 시 해당 게시글의 댓글도 삭제 되도록 수정
=> refactor : 게시글 삭제 시 댓글도 삭제 되도록 수정

.gitignore, src/main/java/com/yht/exerciseassist/domain/comment/controller/CommentController.java, src/main/java/com/yht/exerciseassist/domain/comment/dto/CommentListDto.java, src/main/java/com/yht/exerciseassist/domain/comment/dto/CommentListwithSliceDto.java, src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepository.java, src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepositoryCustom.java, src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepositoryImpl.java, src/main/java/com/yht/exerciseassist/domain/comment/service/CommentService.java, src/main/java/com/yht/exerciseassist/domain/emailCode/EmailCode.java, src/main/java/com/yht/exerciseassist/domain/member/dto/MyMemberPage.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/domain/post/dto/PostListDto.java, src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepository.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java, src/main/java/com/yht/exerciseassist/exception/controller/CommentExceptionController.java, src/main/java/com/yht/exerciseassist/exception/error/ErrorCode.java, src/main/resources/log4j2.xml, src/test/java/com/yht/exerciseassist/domain/comment/controller/CommentControllerTest.java, src/test/java/com/yht/exerciseassist/domain/comment/repository/CommentRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/comment/service/CommentServiceTest.java, src/test/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/factory/CommentFactory.java, src/test/java/com/yht/exerciseassist/domain/likeCount/repository/LikeCountRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/post/service/PostServiceTest.java
댓글 조회 기능 구현, 부모 댓글 삭제 시 대댓글도 삭제되도록 벌크 연산 이용
=> feat(showComment) : 댓글 조회 기능 추가, 대댓글 삭제 기능 추가

src/main/java/com/yht/exerciseassist/domain/comment/Comment.java, src/main/java/com/yht/exerciseassist/domain/comment/service/CommentService.java, src/test/java/com/yht/exerciseassist/domain/comment/controller/CommentControllerTest.java, src/test/java/com/yht/exerciseassist/domain/comment/repository/CommentRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/comment/service/CommentServiceTest.java, src/test/java/com/yht/exerciseassist/domain/factory/CommentFactory.java
=> test : 댓글 조회 테스트 추가

src/main/resources/application-prod.yml
=> chore : https 적용 오류 수정

src/main/java/com/yht/exerciseassist/domain/emailCode/service/EmailService.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/jwt/filter/ExceptionHandlerFilter.java, src/main/java/com/yht/exerciseassist/util/TempPassword.java, src/test/java/com/yht/exerciseassist/domain/factory/EmailCodeFactory.java, src/test/java/com/yht/exerciseassist/domain/member/service/MemberServiceTest.java
이메일 인증 코드가 같은 이메일에서는 달라지지 않는 문제 해결
=> refactor : 이메일 인증 코드 변경 안되는 문제 해결

src/main/java/com/yht/exerciseassist/cron/cronService/EmailCron.java, src/main/java/com/yht/exerciseassist/cron/cronService/RefreshTokenCron.java, src/main/java/com/yht/exerciseassist/domain/emailCode/service/EmailService.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java
=> rename : cron 작업들 분류

src/main/java/com/yht/exerciseassist/cron/cronService/AccuseCron.java, src/main/java/com/yht/exerciseassist/domain/accuse/Accuse.java, src/main/java/com/yht/exerciseassist/domain/accuse/controller/AccuseController.java, src/main/java/com/yht/exerciseassist/domain/accuse/repository/AccuseRepository.java, src/main/java/com/yht/exerciseassist/domain/accuse/service/AccuseService.java, src/main/java/com/yht/exerciseassist/exception/error/ErrorCode.java
=> feat : 2주 지난 신고 자동 삭제 기능 구현

src/main/java/com/yht/exerciseassist/domain/likeCount/repository/LikeCountRepository.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java, src/test/java/com/yht/exerciseassist/domain/likeCount/repository/LikeCountRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/post/service/PostServiceTest.java
=> refactor : 게시글 삭제 기능 수정

src/main/java/com/yht/exerciseassist/cron/cronService/AccuseCron.java, src/main/java/com/yht/exerciseassist/cron/cronService/CommentCron.java, src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepository.java
=> feat : 댓글 정기 삭제 기능 구현

src/main/java/com/yht/exerciseassist/cron/cronService/PostCron.java, src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepository.java
=> feat : 삭제 후 30일 지난 게시글 db에서 삭제

src/main/java/com/yht/exerciseassist/cron/cronService/DiaryCron.java, src/main/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepository.java
삭제 후 30일 지난 다이어리 db에서 삭제되는 기능 구현
=> feat : 삭제 후 30일 지난 다이어리 db에서 삭제

src/main/java/com/yht/exerciseassist/cron/cronService/MemberCron.java, src/main/java/com/yht/exerciseassist/domain/accuse/repository/AccuseRepository.java, src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepository.java, src/main/java/com/yht/exerciseassist/domain/comment/service/CommentService.java, src/main/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepository.java, src/main/java/com/yht/exerciseassist/domain/likeCount/repository/LikeCountRepository.java, src/main/java/com/yht/exerciseassist/domain/media/service/MediaService.java, src/main/java/com/yht/exerciseassist/domain/member/repository/MemberRepository.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepository.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java
=> feat : 탈퇴한 멤버 자동 삭제 기능 구현

src/main/resources/application-prod.yml
서버 주소 변경에 따른 미디어 파일 읽어올 때 사용되는 baseUrl 변경
=> refactor : baseUrl 변경

src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepository.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java
일반 유저가 조회 시 삭제되지 않은 게시글만 조회될 수 있도록 쿼리 수정
=> refactor : post 관련 쿼리 수정

src/main/java/com/yht/exerciseassist/domain/accuse/repository/AccuseRepository.java, src/main/java/com/yht/exerciseassist/domain/accuse/service/AccuseService.java, src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepository.java, src/main/java/com/yht/exerciseassist/domain/comment/service/CommentService.java, src/main/java/com/yht/exerciseassist/domain/diary/controller/DiaryController.java, src/main/java/com/yht/exerciseassist/domain/diary/repository/DiaryRepository.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/emailCode/service/EmailService.java, src/main/java/com/yht/exerciseassist/domain/media/controller/MediaController.java, src/main/java/com/yht/exerciseassist/domain/media/repository/MediaRepository.java, src/main/java/com/yht/exerciseassist/domain/media/service/MediaService.java, src/main/java/com/yht/exerciseassist/domain/member/repository/MemberRepository.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepository.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java, src/main/java/com/yht/exerciseassist/exception/error/ErrorCode.java, src/test/java/com/yht/exerciseassist/domain/comment/service/CommentServiceTest.java, src/test/java/com/yht/exerciseassist/domain/diary/service/DiaryServiceTest.java, src/test/java/com/yht/exerciseassist/domain/media/service/MediaServiceTest.java, src/test/java/com/yht/exerciseassist/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/yht/exerciseassist/domain/member/service/MemberServiceTest.java, src/test/java/com/yht/exerciseassist/domain/post/service/PostServiceTest.java
USER 등급의 회원 조회 시 삭제된 데이터는 조회되지 않도록 canceledAt = null 조건 추가
=> refactor : canceledAt = null 조건 추가

src/test/java/com/yht/exerciseassist/domain/comment/service/CommentServiceTest.java, src/test/java/com/yht/exerciseassist/domain/diary/service/DiaryServiceTest.java, src/test/java/com/yht/exerciseassist/domain/media/service/MediaServiceTest.java, src/test/java/com/yht/exerciseassist/domain/post/service/PostServiceTest.java
쿼리 수정 & repository클래스들의 메서드 변경에 따라 테스트 코드 수정
=> test : 쿼리 수정에 따른 테스트 코드 수정

src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/main/resources/spy.properties
=> chore : 운영환경에서 로그에 sql 출력 수정

src/main/java/com/yht/exerciseassist/seoulAPI/ApiExplorer.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
=> chore : 서버 주소 변경

src/main/java/com/yht/exerciseassist/domain/member/controller/MemberController.java, src/main/java/com/yht/exerciseassist/domain/member/dto/PWDto.java, src/test/java/com/yht/exerciseassist/domain/member/controller/MemberControllerTest.java, src/test/java/com/yht/exerciseassist/domain/member/service/MemberServiceTest.java
멤버 탈퇴 로직에서 비밀번호 인증 과정 추가로 인한 테스트 코드 변경
=> test : 멤버 탈퇴 테스트 코드 변경

src/main/java/com/yht/exerciseassist/domain/member/Member.java, src/main/java/com/yht/exerciseassist/domain/member/controller/MemberController.java, src/main/java/com/yht/exerciseassist/domain/member/dto/EditMemberDto.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java, src/main/java/com/yht/exerciseassist/exception/error/ErrorCode.java
=> feat : 회원정보 수정 기능 추가

src/main/java/com/yht/exerciseassist/domain/member/dto/EditMemberDto.java, src/test/java/com/yht/exerciseassist/domain/member/controller/MemberControllerTest.java, src/test/java/com/yht/exerciseassist/domain/member/service/MemberServiceTest.java
=> test : 회원정보 수정 테스트

src/main/java/com/yht/exerciseassist/domain/accuse/Accuse.java, src/main/java/com/yht/exerciseassist/domain/accuse/controller/AccuseController.java, src/main/java/com/yht/exerciseassist/domain/accuse/service/AccuseService.java, src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepositoryCustom.java, src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepositoryImpl.java, src/main/java/com/yht/exerciseassist/domain/comment/service/CommentService.java
=> feat : 댓글 신고 기능 추가

src/main/java/com/yht/exerciseassist/domain/comment/service/CommentService.java, src/test/java/com/yht/exerciseassist/domain/accuse/controller/AccuseControllerTest.java, src/test/java/com/yht/exerciseassist/domain/accuse/service/AccuseServiceTest.java, src/test/java/com/yht/exerciseassist/domain/factory/AccuseFactory.java
=> test : 댓글 신고 테스트 추가

README.md
=> docs : README.md 작성

src/test/java/com/yht/exerciseassist/ExerciseAssistApplicationTests.java, src/test/java/com/yht/exerciseassist/domain/diary/service/DiaryServiceTest.java, src/test/java/com/yht/exerciseassist/domain/factory/DiaryFactory.java
다이어리 조회에서 DTO 변경으로 인한 테스트 코드 수정
=> test : 다이어리 테스트 수정

src/main/java/com/yht/exerciseassist/domain/comment/controller/CommentController.java, src/main/java/com/yht/exerciseassist/domain/comment/dto/CommentListDto.java, src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepositoryImpl.java, src/main/java/com/yht/exerciseassist/domain/comment/service/CommentService.java
=> refactor : 댓글 조회 긴급 수정

src/main/java/com/yht/exerciseassist/admin/accuse/repository/AdminAccuseRepositoryImpl.java, src/main/java/com/yht/exerciseassist/domain/comment/service/CommentService.java, src/main/java/com/yht/exerciseassist/domain/post/repository/PostRepositoryImpl.java, src/main/java/com/yht/exerciseassist/exception/controller/CommentExceptionController.java, src/main/java/com/yht/exerciseassist/exception/error/ErrorCode.java
=> refactor : 댓글 조회 수정

src/main/java/com/yht/exerciseassist/admin/accuse/controller/AdminAccuseController.java, src/main/java/com/yht/exerciseassist/admin/accuse/repository/AdminAccuseRepository.java, src/main/java/com/yht/exerciseassist/admin/accuse/service/AdminAccuseService.java, src/main/java/com/yht/exerciseassist/domain/accuse/Accuse.java, src/main/java/com/yht/exerciseassist/domain/accuse/controller/AccuseController.java, src/main/java/com/yht/exerciseassist/domain/accuse/repository/AccuseRepository.java, src/main/java/com/yht/exerciseassist/domain/accuse/service/AccuseService.java, src/test/java/com/yht/exerciseassist/admin/accuse/controller/AdminAccuseControllerTest.java, src/test/java/com/yht/exerciseassist/admin/accuse/service/AdminAccuseServiceTest.java
deleteAccuse 코드가 속한 폴더를 domain -> admin 으로 변경, 테스트 추가
=> rename : deleteAccuse 코드 위치 변경, 테스트 추가

README.md
=> refactor : Readme 대소문자 수정

build.gradle, src/main/resources/application-prod.yml, src/main/resources/log4j2.xml
포트 번호 변경, 로컬 로깅 파일 위치 변경 프로젝트 이름 변경
=> refactor : 프로젝트 설정 변경

README.md
=> refactor : readme 개발 도구 추가

src/main/resources/application-prod.yml
=> refactor : 포트번호 원래대로

src/main/resources/application-prod.yml
=> refactor : 포트 번호 변경

src/main/resources/application-prod.yml
=> chore : ec2 배포 환경 설정

src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java
다이어리, 게시글 수정 시 사진을 모두 지우면 반영 안되던 문제 해결
=> fix : 다이어리, 게시글 수정 시 사진 지워도 반영 안되던 문제 해결

src/main/java/com/yht/exerciseassist/configuration/SecurityConfig.java, src/main/java/com/yht/exerciseassist/domain/chat/ChatMessage.java, src/main/java/com/yht/exerciseassist/domain/chat/controller/ChatController.java, src/main/java/com/yht/exerciseassist/domain/chat/repository/ChatListRepository.java, src/main/java/com/yht/exerciseassist/domain/chat/service/ChatService.java
=> fix : 채팅방 생성 시 transaction문제 수정

src/main/java/com/yht/exerciseassist/gpt/routine/controller/RoutineController.java, src/main/java/com/yht/exerciseassist/gpt/routine/dto/DietReq.java, src/main/java/com/yht/exerciseassist/gpt/routine/dto/RoutineReq.java, src/main/java/com/yht/exerciseassist/gpt/routine/service/RoutineService.java
gpt api를 이용한 현재 섭취한 영양소와 그에 따른 식단 추천 기능 개발
=> feat : 식단 추천 기능 구현

src/main/java/com/yht/exerciseassist/domain/member/dto/MyMemberPage.java, src/main/java/com/yht/exerciseassist/domain/member/dto/OtherMemberPage.java, src/main/java/com/yht/exerciseassist/domain/member/service/MemberService.java
마이페이지에서 삭제된 게시글,댓글 포함되어 나오는 문제 수정
=> fix : 마이페이지에서 삭제된 게시글,댓글 포함되어 나오는 문제 수정

src/test/java/com/yht/exerciseassist/domain/member/service/MemberServiceTest.java
=> test : 비밀번호 체크 로직 테스트 추가

src/main/java/com/yht/exerciseassist/domain/diary/ExerciseInfo.java, src/main/java/com/yht/exerciseassist/domain/diary/controller/DiaryController.java, src/main/java/com/yht/exerciseassist/domain/diary/dto/ExerciseInfoDto.java, src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/test/java/com/yht/exerciseassist/domain/factory/DiaryFactory.java
다이어리 작성, 수정 시 운동 부위 여러개 받을 수 있도록 수정
=> fix : 다이어리 작성, 수정 시 운동 부위 여러개 받을 수 있도록 수정

src/main/java/com/yht/exerciseassist/domain/media/service/MediaService.java, src/test/java/com/yht/exerciseassist/domain/member/service/MemberServiceTest.java
=> refactor : 파일 업로드 로직 통합

src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/test/java/com/yht/exerciseassist/domain/diary/service/DiaryServiceTest.java
=> fix : 다이어리 수정 기능 수정

src/main/java/com/yht/exerciseassist/gpt/routine/service/RoutineService.java, src/main/resources/application.yml
=> fix : gpt운동 피드백 프롬프트 수정

src/main/java/com/yht/exerciseassist/domain/diary/service/DiaryService.java, src/main/java/com/yht/exerciseassist/domain/media/service/MediaService.java
=> fix : 이미지 삭제되지 않는 버그 수정

src/main/java/com/yht/exerciseassist/domain/media/service/MediaService.java
=> fix : 같은 이름의 사진 업로드시 중복문제 해결

src/main/java/com/yht/exerciseassist/domain/comment/repository/CommentRepository.java, src/main/java/com/yht/exerciseassist/domain/comment/service/CommentService.java, src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java
깃헙 이슈 게시글 댓글 응답 데이터 수정 요청 #170 해결
=> fix : 게시글 댓글 응답 데이터 수정 요청 #170 해결

src/main/java/com/yht/exerciseassist/domain/post/service/PostService.java
=> fix : 게시글 조회 500에러 해결

README.md, src/main/java/com/yht/exerciseassist/jwt/filter/ExceptionHandlerFilter.java
=> fix : 토큰 발급 수정

src/main/java/com/yht/exerciseassist/exception/CommonExceptionHandler.java, src/main/java/com/yht/exerciseassist/exception/controller/APIExceptionController.java, src/main/java/com/yht/exerciseassist/exception/controller/CommentExceptionController.java, src/main/java/com/yht/exerciseassist/exception/controller/GptExceptionHandler.java
=> refactor : 에러 api 통일
